import type { Metadata } from "next";
import { Geist, Geist_Mono, Fraunces, Herr_Von_Muellerhoff, Allura } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const fraunces = Fraunces({
  variable: "--font-fraunces",
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"],
});

const herrVon = Herr_Von_Muellerhoff({
  variable: "--font-herrVon",
  subsets: ["latin"],
  weight: ["400"],
});

const allura = Allura({
  variable: "--font-allura",
  subsets: ["latin"],
  weight: ["400"], 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${fraunces.variable} ${herrVon.variable} ${allura.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
